on:
  push:
    branches:
      - master

name: Production CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install dependencies
        run: |
          npm install
      - name: Deploy
        run: |
          npx now --name seoul --prod --token $NOW_TOKEN -e JWT_SECRET=$JWT_SECRET -e ADMIN_PASSWORD=$ADMIN_PASSWORD -e FIREBASE_API_KEY=$FIREBASE_API_KEY
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
