on:
  push:
    branches:
      - master

name: Production CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          curl -X POST https://api.zeit.co/v1/integrations/deploy/QmTvPZYMCvbynuBfonn7hgPN8i2gaeoGRWzcBhRM3EUieU/ek0oiv7p3C
